# /Users/mikekrisher/.config/tmuxinator/portal.yml

name: portal
root: /Users/mikekrisher/code/BlueLavaPortal

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
startup_window: portal-editor

windows:
  - portal-editor:
      layout: main-horizontal
      panes:
        - nvim
        - clear
  - portal-server: bers
