# bash compatible
export PATH=$HOME/bin:$PATH

# add crates to path
export PATH=$PATH:/Users/mkrisher/.cargo/bin

# uses neovim
export EDITOR=nvim

# Adds sbin for homebrew
export PATH="/opt/homebrew/bin:/usr/local/sbin:$PATH"

if type brew &>/dev/null; then
  # note, permissions error when linking formulas
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

  autoload -Uz compinit
  compinit
fi

# Set name of the theme to load
ZSH_THEME="apple"

source "$HOME/.cargo/env" # rust package manager

# Preferred Python
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"

# Preferred Ruby
eval "$(rbenv init -)"

# load environment specific files
source ~/.config/.env 
source ~/.config/.aliases

# mimic os x keys for start and end of line
# which don't conflict with tmux keys, requires preferences in iterm
bindkey "[D" backward-word
bindkey "[C" forward-word
bindkey "^[a" beginning-of-line
bindkey "^[e" end-of-line

eval "$(zoxide init zsh)"
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

# puts tailwind ahead of rbenv shim
export PATH="/usr/local/bin:$PATH"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/mkrisher/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/mkrisher/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/mkrisher/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/mkrisher/google-cloud-sdk/completion.zsh.inc'; fi

eval "$(starship init zsh)"

# Created by `pipx` on 2025-03-07 21:18:47
export PATH="$PATH:/Users/mkrisher/.local/bin"
export PATH="/opt/homebrew/opt/llvm/bin:$PATH"

# For compilers to find llvm you may need to set:
export LDFLAGS="-L/opt/homebrew/opt/llvm/lib"
export CPPFLAGS="-I/opt/homebrew/opt/llvm/include"
