# bash compatible
export PATH=$HOME/bin:$PATH

export EDITOR=nvim

# Adds sbin for homebrew
export PATH="/opt/homebrew/bin:/usr/local/sbin:$PATH"

if type brew &>/dev/null; then
  # note, permissions error when linking formulas
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

  autoload -Uz compinit
  compinit
fi

# Path to oh-my-zsh installation
export ZSH="$HOME/.config/oh-my-zsh"

# Set name of the theme to load
ZSH_THEME="apple"

# Which plugins would you like to load?
# Standard plugins can be found in ~/.config/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.config/.oh-my-zsh/custom/plugins/
plugins=(
  git
  ruby 
  zsh-completions
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source "$HOME/oh-my-zsh/oh-my-zsh.sh"
source "$HOME/.cargo/env" # rust package manager

# Preferred Python
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"

# Preferred Ruby
eval "$(rbenv init -)"

# load environment specific files
source ~/.config/.env 
source ~/.config/.aliases

# mimic os x keys for start and end of line
# which don't conflict with tmux keys, requires preferences in iterm
bindkey "[D" backward-word
bindkey "[C" forward-word
bindkey "^[a" beginning-of-line
bindkey "^[e" end-of-line
export PATH="/opt/homebrew/opt/postgresql@13/bin:$PATH"
export PATH="/opt/homebrew/opt/libpq/bin:$PATH"
export PATH="/opt/homebrew/opt/node@16/bin:$PATH"
