# If you come from bash you might have to change your $PATH.
 export PATH=$HOME/bin:$PATH

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin:$HOME/.cargo/bin"

# Adds sbin for homebrew
export PATH="/usr/local/sbin:$PATH"

if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

  autoload -Uz compinit
  compinit
fi

# Path to your oh-my-zsh installation.
export ZSH="$HOME/dotfiles/zsh/oh-my-zsh"

# Set name of the theme to load
ZSH_THEME="apple"

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(git ruby zsh-autosuggestions)

source ~/oh-my-zsh/oh-my-zsh.sh

# Preferred Java
#export PATH="$HOME/.jenv/bin:$PATH"
#eval "$(jenv init -)"

# Preferred Python
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"

# Preferred Ruby
eval "$(rbenv init -)"

export PATH=/usr/local/Cellar/the_silver_searcher/2.2.0/bin:$PATH

# load environment specific files
source ~/.env 
source ~/.aliases

# mimic os x keys for start and end of line
# which don't conflict with tmux keys, requires preferences in iterm
bindkey "[D" backward-word
bindkey "[C" forward-word
bindkey "^[a" beginning-of-line
bindkey "^[e" end-of-line
